<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUJBZixu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUJBZixu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUJBZixu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUJBZixu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUJBZixu\App_KernelDevDebugContainer([
    'container.build_hash' => 'UJBZixu',
    'container.build_id' => '78d18b46',
    'container.build_time' => 1576704702,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUJBZixu');
